name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'
    types: [ opened, synchronize, reopened ]

jobs:
  test-unit-and-integration:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.22.x', '1.x' ]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies 
        run: go mod download

      - name: Run Unit Tests
        run: go test ./internal/...

      - name: Run Integration Tests
        run: go test ./test/integration/...
      
      
  test-e2e-golang:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.22.x' ]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: | 
          cd ./test/e2e/golang
          go mod download

      - name: Run E2E Golang Tests
        env:
          XMR_SPEND_WALLET_PASSWORD: ${{ secrets.XMR_SPEND_WALLET_PASSWORD }}
        run: | 
          cd ./test/e2e/golang
          go test ./test
